name: btw17_sample_scripts
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - pymongo==4.3.3
  - pandas==1.5.2
  - matplotlib==3.6.2
  - jupyter==1.0.0
  - nbstripout==0.5.0
  - qgrid==1.3.1
  - ipywidgets~=7.0
  - pip
  - pip:
    - smm_wrapper



